module.exports =  {
    A002: {
        codetitle: '企业基本信息',
        corpName: '公司名称',
        hisName: '曾用名',
        creditId: '统一社会信用代码',
        regNum: '工商注册号',
        legalRepName: '法定代表人',
        regCap: '注册资本（万元）',
        regCapCur: '注册资本币种',
        establishDate: '成立日期',
        openFrom: '经营期限自',
        openTo: '经营期限至',
        corpType: '公司类型',
        regStatus: '经营状态',
        businessScope: '经营业务范围',
        regOrgCode: '注册地址行政区编号',
        cancelDate: '注销日期',
        revokeDate: '吊销日期',
        accCap: '实收资本（万元）（暂未使用）',
        accCapCur: '实收资本币种（暂未使用）',
        regProvince: '所在省份',
        regCity: '所在城市',
        regRegion: '所在地区',
        description: '企业简介',
        regAddress: '注册地址',
        email: '邮箱',
        telNum: '联系电话',
        website: '网址',
        industryCode: '国民经济行业代码',
        industryName: '国民经济行业名称',
    },
    A003: {
        codetitle: '主要人员',
        total: '主要人员总数',
        id: '人员ID',
        name: '人员姓名',
        title: '职务',
        logo: 'logo',
    },
    A004: {
        total: '股东总数',
        name: '股东名称',
        isMerge: '是否有未完成并购事件(如果yes)',
        beforeMerge: '并购事件完成前股权结构',
        id: '股东ID',
        amount: '认缴出资额（万元）',
        currency: '认缴出资币种',
        date: '出资日期',
        percent: '出资比例',
        shNation: '国别',
        type: '股东类型',
        paymentType: '出资方式',
        afterMerge: '并购事件完成后股权结构',
        codetitle: '股东信息',

    },
    A005: {
        total: '投资企业总数量',
        corpName: '企业（机构）名称',
        creditId: '统一社会信用代码',
        corpType: '企业(机构)类型',
        regCap: '注册资本(万元)',
        regCur: '注册资本币种',
        corpStatus: '企业状态',
        regInstitute: '登记机关',
        amount: '认缴出资额(万元)',
        currency: '认缴出资币种',
        pencent: '出资比例',
        establishDate: '开业日期',
        legalRepName: '法定代表人姓名',
        cancelDate: '注销日期',
        revokeDate: '吊销日期',
        regOrgCode: '注册地址行政区编号',
        codetitle: '对外投资',

    },
    A006: {
        total: '变更总数',
        changeItem: '变更事项',
        changeType: '变更类型',
        changeType: '变更日期',
        changeBefore: '变更前',
        changeAfter: '变更后',
        codetitle: '变更信息',

    },
    A007: {
        total: '年报总数',
        annualReport: '',
        baseinfo: '基本信息',
        reportYear: '年份',
        corpName: '公司名称',
        creditId: '统一社会信用代码',
        regNum: '注册号',
        telNum: '企业联系方式',
        postcode: '邮编',
        postAddress: '通讯地址',
        email: '邮箱',
        corpStatus: '经营状态',
        employeeNum: '从业人数',
        employeeWomen: '其中女性从业人数',
        holdingStatus: '企业控股情况',
        totalEquity: '所有者权益合计',
        totalSales: '营业总收入',
        totalProfit: '利润总额',
        primeProfit: '主营业务收入',
        retainedProfit: '净利润',
        totalTax: '纳税总额',
        totalLiability: '负债总额',
        changeRecordList: '年报变更',
        reportYear: '年份',
        changeItem: '修改事项',
        codetitle: '企业年报',

    },
    A008: {
        total: '分支机构总数',
        corpName: '分支机构名称',
        windId: '分支机构ID',
        creditId: '分支机构统一社会信用代码',
        regNum: '分支机构企业注册号',
        legalRepName: '分支机构法定代表人',
        regOrg: '分支机构登记机关',
        regCap: '分支机构注册资金（万元）',
        regStatus: '分支机构企业状态',
        regProvince: '分支机构所在省份',
        establishDate: '分支机构成立日期',
        codetitle: '分支机构',

    },
    B002: {
        "total": "分支机构总数",
        "corpName": "分支机构名称",
        "windId": "分支机构ID",
        "creditId": "分支机构统一社会信用代码",
        "regNum": "分支机构企业注册号",
        "legalRepName": "分支机构法定代表人",
        "regOrg": "分支机构登记机关",
        "regCap": "分支机构注册资金（万元）",
        "regStatus": "分支机构企业状态",
        "regProvince": "分支机构所在省份",
        "establishDate": "分支机构成立日期",
        "total": "行政许可总数",
        "licenceNum": "行政许可文件编号",
        "licenceName": "行政许可名称",
        "fromDate": "有效期自",
        "toDate": "有效期至",
        "licenceOrg": "许可机关",
        "licenceContent": "许可内容",
        codetitle: '行政许可',

    },
    B003: {
        "total": "商标总数",
        "regNum": "商标注册号",
        "tmName": "商标名称",
        "status": "商标最新状态",
        "tmServContent": "商标服务内容",
        "fromDate": "专用期限自（起始日期）",
        "toDate": "专用期限至（到期日期）",
        "checkDate": "初审公告日",
        "appDate": "申请日期",
        "pubDate": "注册公告日",
        "status": "商标最新状态",
        "tmClass": "国际类别",
        "tmPic": "商标图示",
        codetitle: '商标信息',

    },
    B004: {
        "total": "商标总数",
        "ptName": "专利名称",
        "appDate": "申请日期",
        "appNum": "申请号",
        "pubDate": "公开公告日期",
        "pubNum": "公开公告号",
        "address": "地址",
        "ptStatus": "法律状态",
        "ptType": "专利类型",
        "ptCatNum": "分类号",
        "applicant": "申请（专利权）人",
        "inventor": "发明人",
        "description": "摘要/简要说明",
        "agency": "代理机构",
        "agent": "代理人",
        "mainCatNum": "主分类号",
        "catType": "分类类型",
        "expireDate": "专利届满日",
        "ptPic": "专利图片",
        codetitle: '专利',

    },
    B005: {
        "total": "软件著作权总数",
        "crName": "软件著作权名称",
        "regNum": "登记号",
        "shortName": "简称",
        "version": "版本号",
        "catNum": "分类号",
        "pubDate": "首次发表日期",
        "regApproDate": "登记批准日期",
        "owner": "著作权人",
        codetitle: '软件著作权',

    },
    B006: {
        "total": "作品著作权总数",
        "prodName": "作品名称",
        "regNum": "登记号",
        "type": "作品类别",
        "finishDate": "创作完成日期",
        "pubDate": "首次发表日期",
        "regDate": "登记日期",
        "owner": "著作权人",
        codetitle: '作品著作权',

    },
    B007: {
        "total": "网站总数",
        "webDomain": "网站域名",
        "corpName": "公司名称",
        "webName": "网站名称",
        "license": "网站备案/许可证号",
        "checkDate": "审核通过时间",
        codetitle: '网站备案',

    },
    B008: {
        "total": "微信公众号总数",
        "wechatName": "账号名称",
        "wechatNum": "账号",
        "description": "简介",
        "wechatPic": "头像图片ID",
        "qrcodePic": "二维码图片ID",
        codetitle: '微信公众号',

    },
    B009: {
        "weiboName": "账号名称",
        "weiboID": "账号",
        "description": "简介",
        "weiboPic": "头像图片ID",
        "URL": "账号URL",
        codetitle: '微博账号',

    },
    B010: {
        "total": "全部资质认证",
        "certType": "证书类型",
        "certNum": "证书编号",
        "issueDate": "发证日期",
        "endDate": "截止日期",
        "certStatus": "证书状态",
        "firstCertDate": "初次获证日期",
        "expirationDate": "证书到期日期",
        "supervisionTimes": "监督次数",
        "reauthTimes": "再认证次数",
        "certBasis": "认证依据",
        "standardTech": "认证依据的标准和技术要求",
        "authTag": "证书使用的认可标识",
        "certEmplyeeNum": "认证相关员工数量",
        "coverPlace": "是否覆盖多场所",
        "coverPlaceName": "认证覆盖的场所名称及地址",
        "reportDate": "信息上报日期",
        "revokeDate": "撤销日期",
        "changeDate": "变更日期",
        "cancelDate": "注销日期",
        "productCat": "产品类别",
        "productMainUnit": "产品名称及单元（主）",
        "productSecUnit": "产品名称及单元(次)",
        "model": "规格型号",
        "certScope": "认证覆盖的业务范围",
        "certAgent": "认证委托人",
        codetitle: '资质认证',

    },
    B011: {
        "total": "全部产品数量",
        "corpName": "企业名称",
        "itemName": "商品名称",
        "brandName": "品牌名称",
        "barCode": "商标条码号",
        "origin": "原产国",
        "productSeries": "产品系列",
        "keywords": "关键字",
        "description": "简短描述",
        "unspscCat": "UNSPSC分类",
        codetitle: '产品信息',

    },
    B012: {
        "total": "全部招投标数量",
        "corpName": "企业名称",
        "title": "标题",
        "id": "招投标ID",
        "purchaser": "采购单位",
        "role": "参与角色",
        "lastestAnnoucementDate": "最新公告时间",
        "contentURL": "公告内容",
        codetitle: '招投标信息',

    },
    C002: {
        "corpName": "企业名称",
        "tradeCode": "交易代码",
        "shortName": "证券中文简称",
        "type": "品种类型",
        codetitle: '发行股票',

    },
    C003: {
        "total": "全部发行债券数量",
        "corpName": "企业名称",
        "bondName": "债券简称",
        "realPublishNumber": "发行规模（亿元）",
        "currentBalance": "当前余额（亿元）",
        "interestDate": "起息日",
        "dueDate": "到期日",
        "creditRating": "信用等级",
        "interestRate": "票面利率(%)",
        codetitle: '发行债券（有余额）',

    },
    C004: {
        "total": "全部发行债券数量",
        "corpName": "企业名称",
        "bondName": "债券简称",
        "realPublishNumber": "发行规模（亿元）",
        "currentBalance": "当前余额（亿元）",
        "interestDate": "起息日",
        "dueDate": "到期日",
        "creditRating": "信用等级",
        "interestRate": "票面利率(%)",
        codetitle: '发行债券（全部）',

    },
    C005: {
        "corpName": "企业名称",
        "bondName": "上市板块",
        "applyCode": "申请事项",
        "currentBalance": "申请进度",
        "startDate": "时间",
        "noOfIssueSharesEstimated": "预计发行股数（万股）",
        "noOfIssueCapsEstimated": "预计发行总股本（万股）",
        "totalInvestmen": "募投项目投资总额",
        "recommendOrgan": "保荐机构",
        codetitle: '待上市企业',

    },
    C006: {
        "total": "全部发行ABS数量",
        "corpName": "企业名称",
        "projectName": "项目名称",
        "issuedAmoun": "发行总额（万元）",
        "currency": "币种",
        "startDate": "时间",
        "announceDate": "发行公告日",
        "dueDate": "法定到期日",
        "basicAssetsType": "基础资产总类",
        codetitle: '发行ABS信息',

    },
    C007: {
        "pevc": "PEVC融资数组",
        "total": "全部PEVC融资",
        "corpName": "融资企业名称",
        "financingMoney": "融资金额（万元）",
        "currency": "币种",
        "turnCode": "轮次代码",
        "financingType": "融资方式",
        "investmentCompany": "投资公司名称",
        "financingDate": "融资时间",
        "pevc": "PEVC退出数组",
        "corpName": "投资公司",
        "quitType": "退出方式",
        "amount": "总投资金额(万元)",
        "quitAmount": "账面退出金额(万元)",
        "currency": "币种",
        "returnMultiple": "账面投资回报倍数",
        "quitTime": "退出时间",
        "eventDescription": "事件描述",
        codetitle: 'PEVC投资和退出',

    },
    C008: {
        "total": "并购信息总数",
        "corpName": "企业名称",
        "dealPartRoleCode": "交易方角色",
        "tradeMoney": "交易价值（万元）",
        "quitAmount": "并购方式",
        "purchaserPayment": "支付金额（万元）",
        "returnMultiple": "收购方拟收购股权比例(%)",
        "quitTime": "首次公布时间",
        "eventDescription": "事件描述",
        codetitle: '并购信息',
        "tradeIntroduction":"交易概述",
        "firstAfficheDate":"首次公布时间",
        "currency":"币种",
        "mergeType":"并购方式",
        "planPurchaseSharePercentage":"收购方拟收购股权比例(%)"

    },
    C009: {
        "vouchee": "被担保人",
        "guarantee": "担保人",
        "fromDate": "担保起始日期",
        "toDate": "担保终止日期",
        "amount": "担保金额（万元）",
        "currency": "币种",
        "period": "担保期限（年）",
        "style": "担保方式",
        "bankCompany": "贷款银行",
        "afficheDate": "公告日期",
        codetitle: '担保信息',


    },
    C010: {
        "total": "全部银行授信总数",
        "corpName": "企业名称",
        "afficheDate": "公告日期",
        "endDate": "截止日期",
        "grantedCreditMoney": "授信额度(亿元)",
        "usedGrantedCreditMoney": "使用授信额度(亿元)",
        "notUsedGrantedCreditMoney": "未使用授信额度(亿元)",
        codetitle: '银行授信额度（部分）',

    },
    C011: {
        "total": "全部股权出质",
        "shareHolderName": "股东名称",
        "impawnNumber": "质押数量(万股)",
        "impawnSide": "质押方",
        "afficheDate": "公告日期",
        "impawnState": "是否解押",
        codetitle: '股权出质(上市企业）',

    },
    C012: {
        "corpName": "企业名称",
        "reportDate": "报告期",
        "sumBusinessIncome": "营业总收入",
        "businessIncome": "营业收入",
        "sumBusinessCost": "营业总成本",
        "sumProfit": "利润总额",
        "businessProfit": "营业利润",
        "netProfitOwnedByParent": "归属母公司股东的净利润",
        "subtractBusinessProfit": "减:营业成本",
        "subtractSalesTaxAndAddon": "减:营业税金及附加",
        "subtractSalesCost": "减:销售费用",
        "subtractOverheadExpenses": "减:管理费用",
        "subtractFinacialExpenses": "减:财务费用",
        "plusIncomeExceptBusiness": "加:营业外收入",
        "substractPayoutExceptBusiness": "减：营业外支出",
        "incomeTax": "所得税",
        "netProfit1": "净利润(含少数股东损益)",
        codetitle: '利润表主要指标',

    },
    C013: {
        "corpName": "企业名称",
        "reportDate": "报告期",
        "currencyFund": "货币资金",
        "otherRecievables": "其他应收款",
        "inventory": "存货",
        "sumOfFloatingAsset": "流动资产合计",
        "longShareHoldingInvestment": "长期股权投资",
        "fixAsset": "固定资产",
        "sumOfNonFloatingAsset": "非流动资产合计",
        "sumOfAsset": "资产总计",
        "shortLoan": "短期借款",
        "payableAccount": "应付账款",
        "otherPayoutItem": "其他应付款",
        "sumOfNonFloatingAsset": "流动负债合计",
        "sumOfNonFloatingDebt": "非流动负债合计",
        "sumOfDebt": "负债合计",
        "capitalStock": "股本",
        "noDividendProfit": "未分配利润",
        "sumOfHolderRightsAndInterests2": "股东权益合计(含少数股东权益)",
        "sumOfHolderRightsAndInterests": "负债及股东权益总计",
        "parentHoldersRights": "归属母公司的股东权益",
        codetitle: '资产负债表主要指标',

    },
    C014: {
        "corpName": "企业名称",
        "reportDate": "报告期",
        "sumOfBusinessCash": "经营性现金流",
        "sumOfBusinessCashPayout": "经营活动现金流出小计",
        "netNumberOfBusinessCashPayout2": "经营活动产生的现金流量净额",
        "sumOfOtherBusinessCashIn": "投资活动现金流入小计",
        "sumOfInvestmentCashOut": "投资活动现金流出小计",
        "netCashOfInvestment": "投资活动产生的现金流量净额",
        "sumOfChipingCapital": "筹资性现金流",
        "sumForChippingCapital": "筹资活动现金流出小计",
        "netNumberForChippingCapital": "筹资活动产生的现金流量净额",
        "netProfitOwnedByParent": "归属母公司股东的净利润",
        codetitle: '现金流量表主要指标',

    },
    D002: {
        "total": "裁判文书总数",
        "corpName": "相关公司名称",
        "docId": "裁判文书ID",
        "caseName": "案件标题",
        "caseId": "案号",
        "caseReason": "案由",
        "plaintiff": "原告",
        "defendant": "被告人",
        "agent": "代理人",
        "thirdParties": "第三人",
        "judgeResult": "判决结果",
        "judgeDetail": "判定原文",
        "judgeDate": "判决时间",
        "province": "地区（省份）",
        "court": "执行法院",
        "pubDate": "发布时间",
        "docType": "文书类型",
        codetitle: '裁判文书',

    },
    D003: {
        "total": "裁判文书总数",
        "corpName": "相关公司名称",
        "docId": "裁判文书ID",
        "caseName": "案件标题",
        "caseId": "案号",
        "caseReason": "案由",
        "plaintiff": "原告",
        "defendant": "被告人",
        "agent": "代理人",
        "thirdParties": "第三人",
        "judgeResult": "判决结果",
        "judgeDetail": "判定原文",
        "judgeDate": "判决时间",
        "province": "地区（省份）",
        "court": "执行法院",
        "pubDate": "发布时间",
        codetitle: '裁判文书（合同纠纷/侵权）',

        "docType": "文书类型",
    },
    D004: {
        "total": "法院公告总数",
        "corpName": "相关公司名称",
        "pubType": "公告类型",
        "caseId": "案号",
        "caseReason": "案由",
        "parties": "当事人",
        "pubDate": "公告时间",
        "content": "公告内容",
        "court": "法院名称",
        codetitle: '法院公告',

    },
    D005: {
        "total": "开庭公告总数",
        "corpName": "相关公司名称",
        "pubType": "公告类型",
        "caseId": "案号",
        "caseReason": "案由",
        "parties": "当事人",
        "pubDate": "公告时间",
        "courtDate": "开庭时间",
        "content": "公告内容",
        "court": "法院名称",
        codetitle: '开庭公告',

    },
    D006: {
        "total": "失信信息总数",
        "corpName": "失信人名称",
        "caseId": "案号",
        "gistId": "执行依据文号",
        "performance": "被执行人的执行情况",
        "disruptType": "行为具体情形",
        "court": "执行法院",
        "regDate": "立案时间",
        "province": "省份",
        "pubDate": "发布时间",
        "gistUnit": "作出执行单位",
        "duty": "生效法律文书确定的义务",
        codetitle: '失信信息',

    },
    D009: {
        "total": "被执行人总数",
        "corpName": "被执行人名称",
        "caseId": "案号",
        "execMoney": "执行标的",
        "court": "执行法院",
        "regDate": "立案时间",
        "province": "省份",
        codetitle: '被执行人',

    },
    D010: {
        "total": "行政处罚总数",
        "corpName": "相关企业名称",
        "title": "标题",
        "punishId": "行政处罚决定书文号",
        "punishType": "处罚类别",
        "performance": "处罚事由",
        "punishResult": "违法结果",
        "punishiReason": "处罚依据",
        "departmentName": "行政处罚决定机关名称",
        "decisionDate": "行政处罚决定日期",
        "pubDate": "公示日期",
        codetitle: '一般行政处罚',

    },
    D011: {
        "total": "环保处罚总数",
        "corpName": "相关企业名称",
        "title": "标题",
        "punishId": "行政处罚决定书文号",
        "punishType": "处罚类别",
        "performance": "处罚事由",
        "punishResult": "违法结果",
        "punishiReason": "处罚依据",
        "departmentName": "行政处罚决定机关名称",
        "decisionDate": "行政处罚决定日期",
        "pubDate": "公示日期",
        codetitle: '环保处罚',

    },
    D012: {
        "total": "食药监处罚总数",
        "corpName": "相关企业名称",
        "title": "标题",
        "punishId": "行政处罚决定书文号",
        "punishType": "处罚类别",
        "performance": "处罚事由",
        "punishResult": "违法结果",
        "punishiReason": "处罚依据",
        "departmentName": "行政处罚决定机关名称",
        "decisionDate": "行政处罚决定日期",
        "pubDate": "公示日期",
        codetitle: '食药监处罚',

    },
    D013: {
        "total": "金融监管处罚总数",
        "corpName": "相关企业名称",
        "title": "标题",
        "punishId": "行政处罚决定书文号",
        "punishType": "处罚类别",
        "performance": "处罚事由",
        "penaltyResult": "违法结果",
        "penaltyiReason": "处罚依据",
        "departmentName": "行政处罚决定机关名称",
        "decisionDate": "行政处罚决定日期",
        "pubDate": "公示日期",
        codetitle: '金融监管处罚',

    },
    D014: {
        "total": "严重违法总数",
        "corpName": "相关企业名称",
        "listReason": "列入严重违法企业名单原因",
        "listDate": "列入日期",
        "removeReason": "移出严重违法企业名单原因",
        "removeDate": "移出日期",
        "listDepartment": "作出决定机关",
        "removeDepartment": "作出决定机关(移出)",
        codetitle: '严重违法',

    },
    D015: {
        "total": "司法协助总数",
        "corpName": "被执行人",
        "securityAmount": "股权数额",
        "currency": "币种",
        "executeNoticeId": "执行通知文书号",
        "court": "执行法院",
        "typeStatus": "类型状态",
        codetitle: '司法协助',

    },
    D016: {
        "total": "司法拍卖总数",
        "corpName": "相关公司名称",
        "title": "拍卖公告标题",
        "scopeDate": "拍卖日期",
        "auctionDescription": "拍品现状描述",
        "court": "拍卖法院",
        "auctionName": "拍品名称",
        "auctionResult": "拍卖结果",
        "targetDescription": "标的介绍",
        "auctionStatus": "拍卖状态",
        "doc": "提供的文件",
        "auctionRound": "拍卖轮次",
        "initialPrice": "起拍价",
        "deposit": "保证金",
        "consultPrice": "评估价",
        "increase": "增加幅度",
        "judicialResource": "权利来源",
        "fromDate": "拍卖开始时间",
        "toDate": "拍卖结束时间",
        codetitle: '司法拍卖',

    },
    D017: {
        "total": "刑事处罚总数",
        "corpName": "相关企业名称",
        "title": "标题",
        "punishId": "刑事处罚决定书文号",
        "punishType": "处罚类别",
        "performance": "处罚事由",
        "punishResult": "违法结果",
        "punishiReason": "处罚依据",
        "departmentName": "刑事处罚决定机关名称",
        "decisionDate": "行政处罚决定日期",
        "pubDate": "公告日期",
        codetitle: '刑事处罚',

    },
    D018: {
        "total": "全部欠税信息总数",
        "corpName": "纳税人名称",
        "taypayerId": "纳税人识别号",
        "owingType": "欠税类型",
        "taxType": "欠税税种",
        "taxBalance": "欠税余额",
        "legalRepName": "法定代表人姓名",
        "legalRepIdNum": "法定代表人证件号",
        "address": "经营地址",
        "publicNum": "公告期次",
        "fromDate": "欠税开始日期",
        "toDate": "欠税截止日期",
        "department": "主管税务机关",
        "pubDate": "公告日期",
        codetitle: '欠税信息',

    },
    D019: {
        "total": "全部税收违法总数",
        "corpName": "纳税人名称",
        "ilegalDetail": "主要违法事实",
        "gistPunish": "相关法律依据及税务处理处罚情况",
        "pubDate": "发布日期",
        "property": "案件性质",
        "ilegalFact": "主要违法事实",
        "department": "实施检查单位 ",
        codetitle: '税收违法',

    },
    D020: {
        "total": "历史处罚总数",
        "corpName": "相关企业名称",
        "title": "标题",
        "punishId": "历史处罚决定书文号",
        "punishType": "处罚类别",
        "performance": "处罚事由",
        "punishResult": "违法结果",
        "punishiReason": "处罚依据",
        "departmentName": "历史处罚决定机关名称",
        "decisionDate": "历史处罚决定日期",
        "pubDate": "公示日期",
        codetitle: '历史处罚',

    },
    E002: {
        "total": "法定代表人变更总数",
        "corpName": "公司名称",
        "pubDate": "发生日期",
        "execName": "法定代表人姓名",
        "jobTitle": "职位",
        "changeType": "变更类型（任职，离职）",
        codetitle: '法定代表人变更',

    },
    E003: {
        "corpName": "公司名称",
        "pubDate": "发生日期",
        "shareholderChange": "高管变动",
        "shareholderName": "股东姓名",
        "shareholderType": "股东类型（1个人，2公司）",
        "changeType": "变更类型",
        "beforeChange": "变更前",
        "securityAmount": "变更前认缴金额（万元）",
        "currency": "币种",
        "percent": "变更前持股比例",
        "afterChange": "变更后",
        "securityAmount": "变更后认缴金额（万元）",
        "currency": "币种",
        "percent": "变更后持股比例",
        codetitle: '股东股权变动',

    },
    E004: {
        "corpName": "公司名称",
        "pubDate": "发生日期",
        "investmentChange": "",
        "investName": "投资企业名称",
        "investId": "投资企业Id",
        "changeType": "变更类型",
        "beforeChange": "变更前",
        "investAmount": "变更前投资金额（万元）",
        "currency": "币种",
        "percent": "变更前持股比例",
        "afterChange": "变更后",
        "investAmount": "变更后投资金额（万元）",
        "currency": "币种",
        "percent": "变更后持股比例",
        codetitle: '对外投资变动',

    },
    E005: {
        "corpName": "公司名称",
        "pubDate": "发生日期",
        "oldControllerName": "变更前实际控股人名称",
        "oldPercent": "控股比例",
        "newControllerName": "变更后实际控制人名称",
        "newPercent": "控股比例",
        codetitle: '企业实际控制人变动',

    },
    E006: {
        "corpName": "公司名称",
        "pubDate": "发生日期",
        "changeType": "变更类型（新增，退出）",
        "branchName": "分支机构名称",
        "branchId": "分支机构ID",
        codetitle: '企业分支机构变动',

    },
    E007: {
        "corpName": "公司名称",
        "pubDate": "发生日期",
        "execName": "高管姓名",
        "jobTitle": "职位",
        "changeType": "变更类型（任职，离职）",
        codetitle: '高管变更',

    },
    E008: {
        "total": "动产抵押总数",
        "basicInfo": "",
        "corpName": "企业名称",
        "regNum": "登记编号",
        "regDate": "登记日期",
        "regOrg": "登记机关",
        "type": "被担保债权种类",
        "amount": "被担保债权数额",
        "currency": "被担保债权币种",
        "regStatus": "登记状态",
        "period": "债务人履行债务期限",
        "scope": "担保范围",
        "pubDate": "公示日期",
        "pledgeeInfo": "",
        "pledgeeName": "抵押权人名称",
        "pledgeeIdType": "抵押权人证件类型",
        "pledgeeId": "抵押劝人证件号码",
        "guaranteeInfo": "",
        "guaranteeName": "抵押物品名称",
        "guaranteeOwnership": "所有权归属",
        "guaranteeDetail": "抵押物情况描述（数量、质量、状况、所在地等情况)",
        "guaranteeRemark": "备注",
        codetitle: '动产抵押(工商信息)',

    },
    E009: {
        "total": "股权出质总数",
        "pledgorName": "出质人",
        "pubDate": "公示日期",
        "regNum": "登记编号",
        "pledgorId": "出质人证照/证件号码",
        "pledgeAmount": "出质股权数额（万股）",
        "pledgeeName": "质权人",
        "pledgeeId": "质权人证照/证件号码",
        "regDate": "股权出质设立登记日期",
        codetitle: '股权出质(工商信息)',

    },
    E010: {
        "certAgent": "认证委托人/获证组织",
        "certType": "证书类型",
        "certNum": "证书编号",
        "productMainUnit": "产品名称及单元（主）",
        "productSecUnit": "产品名称及单元(次)",
        "issueDate": "发证日期",
        "endDate": "截止日期",
        "certStatus": "证书状态",
        "firstCertDate": "初次获证日期",
        "expirationDate": "证书到期日期",
        "supervisionTimes": "监督次数",
        "reauthTimes": "再认证次数",
        "certBasis": "认证依据",
        "standardTech": "认证依据的标准和技术要求",
        "authTag": "证书使用的认可标识",
        "certEmplyeeNum": "认证相关员工数量",
        "coverPlace": "是否覆盖多场所",
        "coverPlaceName": "认证覆盖的场所名称及地址",
        "reportDate": "信息上报日期",
        "revokeDate": "撤销日期",
        "changeDate": "变更日期",
        "cancelDate": "注销日期",
        "productCat": "产品类别",
        "model": "规格型号",
        "certScope": "认证覆盖的业务范围",
        codetitle: '资质认证到期风险',

    },
    E011: {
        "regNum": "商标注册号",
        "tmName": "商标名称",
        "status": "商标最新状态",
        "tmServContent": "商标服务内容",
        "fromDate": "专用期限自（起始日期）",
        "toDate": "专用期限至（到期日期）",
        "checkDate": "初审公告日",
        "appDate": "申请日期",
        "pubDate": "注册公告日",
        "status": "商标最新状态",
        "tmClass": "国际类别",
        "tmPic": "商标图示",
        codetitle: '商标到期风险',

    },
    E012: {
        "ptName": "专利名称",
        "expireDate": "专利届满日",
        "appDate": "申请日期",
        "appNum": "申请号",
        "pubDate": "公开公告日期",
        "pubNum": "公开公告号",
        "address": "地址",
        "ptStatus": "法律状态",
        "ptType": "专利类型（失效）",
        "ptCatNum": "分类号",
        "applicant": "申请（专利权）人",
        "inventor": "发明人",
        "description": "摘要/简要说明",
        "agency": "代理机构",
        "agent": "代理人",
        "mainCatNum": "主分类号",
        "catType": "分类类型",
        "ptPic": "专利图片",
        codetitle: '专利到期风险',

    },
    E013: {
        "total": "抽查检查总数",
        "corpName": "相关企业名称",
        "checkDate": "检查日期",
        "checkOrg": "检查实施机关",
        "checkType": "检查类型",
        "checkResult": "检查结果",
        "remark": "备注",
        codetitle: '抽查检查',

    },
    E014: {
        "total": "简易注销总数",
        "corpName": "企业名称",
        "creditId": "统一社会信用代码/注册号",
        "fromDate": "公告期自",
        "toDate": "公告期至",
        "regOrg": "登记机关",
        "cancellationResult": "简易注销结果",
        codetitle: '简易注销',
    },
    F001: {
        "total": "全部负面新闻数量",
        "corpName": "企业名称",
        "newsTag": "新闻标签",
        "pubDate": "新闻时间（时分秒）",
        "abstract": "新闻摘要",
        "newsURL": "新闻全文URL",
        codetitle: '负面新闻',
    },
    // I002: {
    //     codetitle: '股东及出资信息',
    //     "corpName": "公司名称",
    //     "total": "直接股东数量",
    //     "children": "股东穿透列表",
    //     "name": "公司名称/人员名称",
    //     "level": "股东层级",
    //     "percent": "直接持股比例",
    //     "indirectPercent": "间接持股比例",
    //     "type": "股东类型（1个人，2公司）",
    // },
    // I003: {
    //     codetitle: '企业对外投资',
    //     "corpName": "公司名称",
    //     "total": "直接对外投资数量",
    //     "children": "对外投资穿透列表",
    //     "corpName": "公司名称",
    //     "level": "对外投资层级",
    //     "percent": "直接投资比例",
    //     "indirectPercent": "间接投资比例",
    // },
    // I004: {
    //     codetitle: '主要人员对外任职',
    //     "corpName": "公司名称",
    //     "total": "直接对外投资数量",
    //     "children": "对外投资穿透列表",
    //     "corpName": "公司名称",
    //     "level": "对外投资层级",
    //     "percent": "直接投资比例",
    //     "indirectPercent": "间接投资比例",

    // }





















    // ====A003

}
